spring.application.name=pedidos-api


#Spring Config properties
spring.config.import=optional:file:.env[.properties]

# PostgreSQL Configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${KEY_POSTGRES_USER}
spring.datasource.password=${KEY_POSTGRES_PASSWORD}
spring.datasource.url=jdbc:postgresql://localhost:${KEY_POSTGRES_PORT}/${KEY_POSTGRES_DBL}

# JPA Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgresPlusDialect
spring.jpa.show-sql=true